import AppKit
import CryptoKit

@MainActor
final class ClipboardService {
    private let pasteboard: NSPasteboard
    private var timer: Timer?
    private var lastChange: Int
    var onCapture: ((Clip) -> Void)?
    var onSkip: ((String) -> Void)?
    var ignoredBundleIDs: Set<String> = []
    var paused = false
    nonisolated static let maxBytes = 20 * 1024 * 1024
    nonisolated static let sensitiveTypes: Set<String> = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword"]
    nonisolated static let defaultIgnored = ["com.1password.1password", "com.agilebits.onepassword7", "com.bitwarden.desktop", "com.apple.Passwords", "com.keepassxc.keepassxc", "org.keepassxc.keepassxc", "com.dashlane.Dashlane"]

    init(pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
        lastChange = pasteboard.changeCount // Never ingest the pre-existing clipboard at launch.
    }
    func start() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.65, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer?.tolerance = 0.2
    }
    func stop() { timer?.invalidate(); timer = nil }
    func poll() {
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        guard !paused else { return }
        let source = NSWorkspace.shared.frontmostApplication
        let bundle = source?.bundleIdentifier ?? ""
        guard !ignoredBundleIDs.contains(bundle), bundle != Bundle.main.bundleIdentifier else { return }
        guard let items = pasteboard.pasteboardItems, !items.isEmpty else { return }
        if items.contains(where: { !Self.sensitiveTypes.isDisjoint(with: $0.types.map(\.rawValue)) }) { return }
        do {
            if let clip = try Self.capture(items: items, sourceApp: source?.localizedName ?? "Unknown app", bundleID: bundle) { onCapture?(clip) }
        } catch { onSkip?(error.localizedDescription) }
    }
    enum CaptureError: LocalizedError { case tooLarge
        var errorDescription: String? { "A clipboard item exceeded the 20 MB limit and was skipped." }
    }
    static func capture(items: [NSPasteboardItem], sourceApp: String, bundleID: String) throws -> Clip? {
        var count = 0
        var saved: [[ClipRepresentation]] = []
        let allowed: Set<NSPasteboard.PasteboardType> = [.string, .rtf, .rtfd, .html, .png, .tiff, .fileURL, .URL, .pdf]
        for item in items {
            if !sensitiveTypes.isDisjoint(with: item.types.map(\.rawValue)) { return nil }
            var reps: [ClipRepresentation] = []
            for type in item.types where allowed.contains(type) {
                guard let data = item.data(forType: type) else { continue }
                count += data.count
                guard count <= maxBytes else { throw CaptureError.tooLarge }
                reps.append(ClipRepresentation(type: type.rawValue, data: data))
            }
            if !reps.isEmpty { saved.append(reps.sorted { $0.type < $1.type }) }
        }
        guard !saved.isEmpty else { return nil }
        let all = saved.flatMap { $0 }
        func first(_ type: NSPasteboard.PasteboardType) -> Data? { all.first { $0.type == type.rawValue }?.data }
        var text = first(.string).flatMap { String(data: $0, encoding: .utf8) } ?? ""
        if text.isEmpty, let rtf = first(.rtf), let attr = NSAttributedString(rtf: rtf, documentAttributes: nil) { text = attr.string }
        let fileURLs = all.filter { $0.type == NSPasteboard.PasteboardType.fileURL.rawValue }.compactMap { String(data: $0.data, encoding: .utf8) }
        let urlText = first(.URL).flatMap { String(data: $0, encoding: .utf8) }
        if text.isEmpty { text = urlText ?? fileURLs.joined(separator: "\n") }
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        let kind: ClipKind
        let title: String
        if !fileURLs.isEmpty {
            kind = .file
            title = fileURLs.count > 1 ? "\(fileURLs.count) files" : (URL(string: fileURLs[0])?.lastPathComponent ?? "File")
        } else if first(.png) != nil || first(.tiff) != nil || first(.pdf) != nil {
            kind = .image; title = first(.pdf) != nil ? "PDF document" : "Image"
        } else if trimmed.range(of: "^#[0-9a-fA-F]{6}([0-9a-fA-F]{2})?$", options: .regularExpression) != nil {
            kind = .color; title = trimmed.uppercased()
        } else if let url = URL(string: trimmed), ["http", "https", "mailto"].contains(url.scheme?.lowercased() ?? ""), !trimmed.contains(where: \.isWhitespace) {
            kind = .link; title = url.host ?? trimmed
        } else {
            guard !trimmed.isEmpty else { return nil }
            kind = .text; title = String(trimmed.split(separator: "\n").first.map(String.init)?.prefix(100) ?? "Text")
        }
        let payload = ClipPayload(items: saved)
        let encoder = JSONEncoder(); encoder.outputFormatting = .sortedKeys
        let digest = SHA256.hash(data: try encoder.encode(payload)).map { String(format: "%02x", $0) }.joined()
        return Clip(kind: kind, title: title, text: text, sourceApp: sourceApp, sourceBundleID: bundleID, fingerprint: digest, payload: payload)
    }
    @discardableResult func write(_ clips: [Clip], plain: Bool) -> Bool {
        guard !clips.isEmpty else { return false }
        let items: [NSPasteboardItem]
        if plain {
            let item = NSPasteboardItem()
            let text = clips.map(\.text).filter { !$0.isEmpty }.joined(separator: "\n")
            guard !text.isEmpty else { return false }
            item.setString(text, forType: .string)
            items = [item]
        } else {
            var prepared: [NSPasteboardItem] = []
            for reps in clips.flatMap(\.payload.items) {
                guard !reps.isEmpty else { return false }
                let item = NSPasteboardItem()
                for rep in reps {
                    guard !rep.type.isEmpty, item.setData(rep.data, forType: .init(rep.type)) else { return false }
                }
                prepared.append(item)
            }
            guard !prepared.isEmpty else { return false }
            items = prepared
        }
        pasteboard.clearContents()
        let success = pasteboard.writeObjects(items)
        lastChange = pasteboard.changeCount
        return success
    }
}
